const mongoose = require("mongoose");
const bankSchema = new mongoose.Schema(
  {
    bankName: String,
    accountHolderName: String,
    accountNumber: String,
    ifscCode: String,
    branchName: String,
  },
  { _id: false },
);
const upiSchema = new mongoose.Schema(
  { upiId: String, qrCodeImage: String },
  { _id: false },
);
const schema = new mongoose.Schema(
  {
    storeCode: { type: String, unique: true, required: true },
    storeName: { type: String, required: true },
    ownerName: { type: String, required: true },
    logo: String,
    email: { type: String, lowercase: true },
    phone: { type: String, required: true },
    alternatePhone: String,
    gstNumber: { type: String, uppercase: true },
    panNumber: { type: String, uppercase: true },
    fssaiNumber: String,
    address: { type: String, required: true },
    city: { type: String, required: true },
    state: { type: String, required: true },
    country: { type: String, default: "India" },
    pincode: { type: String, required: true },
    manager: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    openingTime: { type: String, default: "09:00 AM" },
    closingTime: { type: String, default: "09:00 PM" },
    currency: { type: String, default: "INR" },
    currencySymbol: { type: String, default: "₹" },
    invoicePrefix: { type: String, default: "INV" },
    purchasePrefix: { type: String, default: "PUR" },
    barcodePrefix: { type: String, default: "BAR" },
    taxType: { type: String, enum: ["GST", "VAT"], default: "GST" },
    bankDetails: bankSchema,
    upiDetails: upiSchema,
    printerName: String,
    thermalPrinterWidth: { type: Number, default: 80 },
    receiptFooter: { type: String, default: "Thank You! Visit Again." },
    isHeadOffice: { type: Boolean, default: false },
    allowNegativeStock: { type: Boolean, default: false },
    enableBarcode: { type: Boolean, default: true },
    enableLoyalty: { type: Boolean, default: true },
    enableCoupon: { type: Boolean, default: true },
    enableWhatsAppInvoice: { type: Boolean, default: true },
    status: { type: String, enum: ["active", "inactive"], default: "active" },
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    updatedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
  },
  { timestamps: true, versionKey: false },
);
module.exports = mongoose.model("Store", schema);
